restgram:
  build: .
  command: node_modules/.bin/nodemon main.js
  environment:
    NODE_ENV: development
    LOG_LEVEL: silly
    AUTH_DATA: ../authdata.json
    PHONE: ''
    API_ID: ''
    API_HASH: ''
  ports:
    - '3000:3000'
  volumes:
    - .:/home/restgram/data
    - /home/restgram/data/node_modules
